service: load-image-api${opt:developerStack,''}

plugins:
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region,'us-east-1'}
  stage: ${opt:stage,'develop'}
environment:
  ENV: ${self:provider.stage}
  SERVICE: ${self:service}
  REGION: ${self:provider.region}
  IMAGE_TABLE: ${self:service}-${self:provider.stage}-image-table

custom:
  DEFAULT_STAGE: local
  ### Uso local de la dynamo
  serverless-offline:
    httpPort: 9090
  dynamodb:
    stages:
      - develop
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

functions:
  - ${file(src/components/imageValidation/imageValidation.yml)}

resources:
  # Dynamodb table
  - ${file(resources/table/tableImages.yml)}
