service: load-image-api${opt:developerStack,''}

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  
provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region,'us-east-1'}
  stage: ${opt:stage, 'develop'}
  environment:
    ENV: ${self:provider.stage}
    SERVICE: ${self:service}
    REGION: ${self:provider.region}
    ## dynamodb
    IMAGE_TABLE: ${self:service}-${self:provider.stage}-image-table
    ## aws credential
    ACCESS_KEY: AKIATKGSMOIUTWJYEINQ
    SECRET_KEY: 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

custom:
  DEFAULT_STAGE: local
  ## serverless
  serverless-offline:
    httpPort: 9090
  ## dynamo
  dynamodb:
    stages:
      - develop
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      migrate: true
      seed: true
      convertEmptyValues: true

functions:
  ## image validation
  - ${file(src/components/imageValidation/imageValidation.yml)}

resources:
  ## dynamodb table
  - ${file(resources/table/imagesTable.yml)}

